services:
  data_science:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        USER_NAME: ${USER_NAME}
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
      #no_cache: true
    image: data-science-template:latest
    env_file:
      - .env # loads the environment variables
    container_name: data-science-container
    user: "${USER_NAME}"
    volumes:
      - .:/app  # Mount the current directory to /app in the container
      - ./custom_startup.sh:/usr/local/bin/custom_startup.sh
    ports:
      - "8888:8888"  # Jupyter port
      - "8503:8501" # Streamlit port mapped to different on host to not interfere with other app
    environment:
      - JUPYTER_TOKEN=easy
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
      - USER_NAME=${USER_NAME}
      - PYTHONPATH=/src/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - START_JUPYTER=yes
      - START_STREAMLIT=yes
      - STREAMLIT_APP_PATH=webapp/streamlit_demo.py
      
    entrypoint: ["/usr/local/bin/custom_startup.sh"]
    command: ["tail", "-f", "/dev/null"]