[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "deps-only"
version = "0.0.0"
requires-python = ">=3.12"
# Copy the same dependencies you lock (no local package here)
dependencies = [
  "numpy>=1.24.0",
  "pandas>=2.0.0",
  "scipy>=1.10.0",
  "duckdb>=0.9.0",
  "pyarrow>=14.0.1",
  "plotly>=5.13.0",
  "matplotlib>=3.7.0",
  "seaborn>=0.12.0",
  "jupyter>=1.0.0",
  "jupyterlab>=4.0.0",
  "ipywidgets>=8.0.0",
  "jupyter-dash>=0.4.2",
  "scikit-learn>=1.2.0",
  "statsmodels>=0.13.5",
  "tqdm>=4.65.0",
  "requests>=2.31.0",
  "anthropic>=0.8.0",
  "openai>=1.61.1",
  "groq>=0.20.0",
  "pytest>=7.3.1",
  "langchain>=0.3.27",
  "langchain-chroma>=0.2.5",
  "chromadb>=1.0.20",
  "langchain-openai>=0.3.32",
  "sentence-transformers>=5.1.0",
  "tiktoken>=0.11.0",
  "beautifulsoup4>=4.12.0",
  "lxml>=4.9.0",
  "newspaper3k>=0.2.8",
  "trafilatura>=1.6.1",
  "streamlit>=1.31.0",
  "PyYAML==6.0.1",
  "ipython>=8.14.0",
  "kagglehub>=0.3.12",
]